### ISSUE TITLE
Modular scale in headlines

### ISSUE THREAD

**Issue by jonathanhefner** [programble/writ#13]
Have you considered using [modular scale](http://alistapart.com/article/more-meaningful-typography) in your headlines?  Here are a few handy calculators if you'd like to play around with sizes:
- http://www.modularscale.com/
- http://type-scale.com/

For a base font size of 14-16px, I think a ratio of 1.2 (a "minor third") yields nice results.  That would imply the following sizes:

``` css
h1 { font-size: 2.488em; }
h2 { font-size: 2.074em; }
h3 { font-size: 1.728em; }
h4 { font-size: 1.44em; }
h5 { font-size: 1.2em; }
h6 { font-size: 1em; }
```
